from fastf1 import FastAPI

app = FastAPI(title="HR Domain")

HR_data = [
    {"FirstName": "John", "LastName": "Doe", "Role": "Data Engineer", "Age": 24, "Glasses": True},
    {"FirstName": "Alice", "LastName": "Smith", "Role": "Data Scientist", "Age": 31, "Glasses": False},
    {"FirstName": "Michael", "LastName": "Brown", "Role": "Backend Developer", "Age": 28, "Glasses": True},
    {"FirstName": "Emma", "LastName": "Johnson", "Role": "Product Manager", "Age": 35, "Glasses": False},
    {"FirstName": "David", "LastName": "Taylor", "Role": "DevOps Engineer", "Age": 41, "Glasses": True},
    {"FirstName": "Sophia", "LastName": "Anderson", "Role": "Business Analyst", "Age": 26, "Glasses": False},
    {"FirstName": "James", "LastName": "Thomas", "Role": "QA Engineer", "Age": 29, "Glasses": True},
    {"FirstName": "Olivia", "LastName": "Jackson", "Role": "UX Designer", "Age": 33, "Glasses": False},
    {"FirstName": "Daniel", "LastName": "White", "Role": "Data Engineer", "Age": 38, "Glasses": True},
    {"FirstName": "Isabella", "LastName": "Harris", "Role": "HR Specialist", "Age": 27, "Glasses": False},

    {"FirstName": "Liam", "LastName": "Martin", "Role": "Backend Developer", "Age": 34, "Glasses": True},
    {"FirstName": "Mia", "LastName": "Thompson", "Role": "Data Scientist", "Age": 30, "Glasses": False},
    {"FirstName": "Noah", "LastName": "Garcia", "Role": "DevOps Engineer", "Age": 36, "Glasses": True},
    {"FirstName": "Ava", "LastName": "Martinez", "Role": "Product Manager", "Age": 42, "Glasses": False},
    {"FirstName": "Lucas", "LastName": "Robinson", "Role": "Software Architect", "Age": 45, "Glasses": True},
    {"FirstName": "Charlotte", "LastName": "Clark", "Role": "UX Designer", "Age": 29, "Glasses": False},
    {"FirstName": "Henry", "LastName": "Rodriguez", "Role": "Backend Developer", "Age": 32, "Glasses": True},
    {"FirstName": "Amelia", "LastName": "Lewis", "Role": "Business Analyst", "Age": 28, "Glasses": False},
    {"FirstName": "Benjamin", "LastName": "Lee", "Role": "Data Engineer", "Age": 37, "Glasses": True},
    {"FirstName": "Evelyn", "LastName": "Walker", "Role": "HR Specialist", "Age": 34, "Glasses": False},

    {"FirstName": "William", "LastName": "Hall", "Role": "DevOps Engineer", "Age": 40, "Glasses": True},
    {"FirstName": "Harper", "LastName": "Allen", "Role": "QA Engineer", "Age": 25, "Glasses": False},
    {"FirstName": "Alexander", "LastName": "Young", "Role": "Backend Developer", "Age": 39, "Glasses": True},
    {"FirstName": "Ella", "LastName": "Hernandez", "Role": "Data Scientist", "Age": 27, "Glasses": False},
    {"FirstName": "Sebastian", "LastName": "King", "Role": "Software Architect", "Age": 48, "Glasses": True},
    {"FirstName": "Grace", "LastName": "Wright", "Role": "UX Designer", "Age": 31, "Glasses": False},
    {"FirstName": "Jack", "LastName": "Lopez", "Role": "Backend Developer", "Age": 35, "Glasses": True},
    {"FirstName": "Chloe", "LastName": "Hill", "Role": "Product Manager", "Age": 38, "Glasses": False},
    {"FirstName": "Owen", "LastName": "Scott", "Role": "DevOps Engineer", "Age": 29, "Glasses": True},
    {"FirstName": "Zoe", "LastName": "Green", "Role": "Business Analyst", "Age": 26, "Glasses": False},

    {"FirstName": "Leo", "LastName": "Adams", "Role": "Data Engineer", "Age": 33, "Glasses": True},
    {"FirstName": "Lily", "LastName": "Baker", "Role": "QA Engineer", "Age": 24, "Glasses": False},
    {"FirstName": "Julian", "LastName": "Gonzalez", "Role": "Backend Developer", "Age": 41, "Glasses": True},
    {"FirstName": "Nora", "LastName": "Nelson", "Role": "HR Specialist", "Age": 36, "Glasses": False},
    {"FirstName": "Mateo", "LastName": "Carter", "Role": "DevOps Engineer", "Age": 34, "Glasses": True},
    {"FirstName": "Riley", "LastName": "Mitchell", "Role": "UX Designer", "Age": 28, "Glasses": False},
    {"FirstName": "Aaron", "LastName": "Perez", "Role": "Data Scientist", "Age": 37, "Glasses": True},
    {"FirstName": "Hannah", "LastName": "Roberts", "Role": "Product Manager", "Age": 43, "Glasses": False},
    {"FirstName": "Ethan", "LastName": "Turner", "Role": "Backend Developer", "Age": 31, "Glasses": True},
    {"FirstName": "Layla", "LastName": "Phillips", "Role": "Business Analyst", "Age": 27, "Glasses": False},

    {"FirstName": "Isaac", "LastName": "Campbell", "Role": "Data Engineer", "Age": 39, "Glasses": True},
    {"FirstName": "Scarlett", "LastName": "Parker", "Role": "UX Designer", "Age": 32, "Glasses": False},
    {"FirstName": "Wyatt", "LastName": "Evans", "Role": "DevOps Engineer", "Age": 44, "Glasses": True},
    {"FirstName": "Penelope", "LastName": "Edwards", "Role": "HR Specialist", "Age": 29, "Glasses": False},
    {"FirstName": "Nathan", "LastName": "Collins", "Role": "Backend Developer", "Age": 36, "Glasses": True},
    {"FirstName": "Aurora", "LastName": "Stewart", "Role": "Data Scientist", "Age": 34, "Glasses": False},
    {"FirstName": "Caleb", "LastName": "Sanchez", "Role": "QA Engineer", "Age": 26, "Glasses": True},
    {"FirstName": "Violet", "LastName": "Morris", "Role": "Business Analyst", "Age": 30, "Glasses": False},
    {"FirstName": "Ryan", "LastName": "Rogers", "Role": "Product Manager", "Age": 47, "Glasses": True},
    {"FirstName": "Stella", "LastName": "Reed", "Role": "UX Designer", "Age": 28, "Glasses": False},

    {"FirstName": "Luke", "LastName": "Cook", "Role": "Backend Developer", "Age": 35, "Glasses": True},
    {"FirstName": "Elena", "LastName": "Morgan", "Role": "Data Engineer", "Age": 41, "Glasses": False},
    {"FirstName": "Jordan", "LastName": "Bell", "Role": "DevOps Engineer", "Age": 38, "Glasses": True},
    {"FirstName": "Paisley", "LastName": "Murphy", "Role": "HR Specialist", "Age": 27, "Glasses": False},
    {"FirstName": "Connor", "LastName": "Bailey", "Role": "QA Engineer", "Age": 33, "Glasses": True},
    {"FirstName": "Naomi", "LastName": "Rivera", "Role": "Data Scientist", "Age": 29, "Glasses": False},
    {"FirstName": "Adrian", "LastName": "Cooper", "Role": "Backend Developer", "Age": 42, "Glasses": True},
    {"FirstName": "Brooklyn", "LastName": "Richardson", "Role": "Business Analyst", "Age": 31, "Glasses": False},
    {"FirstName": "Thomas", "LastName": "Cox", "Role": "Software Architect", "Age": 50, "Glasses": True},
    {"FirstName": "Madison", "LastName": "Howard", "Role": "Product Manager", "Age": 39, "Glasses": False}
]
